server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customers
          uri: lb://customers
          predicates:
            - Path=/customers/**
        - id: accounts
          uri: lb://accounts
          predicates:
            - Path=/accounts/**
        - id: transactions
          uri: lb://transactions
          predicates:
            - Path=/transactions/**