server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: ${MYSQL_TRANSACTIONS_AXON_JDBC_URL}
    username: ${MYSQL_TRANSACTIONS_AXON_JDBC_USER}
    password: ${MYSQL_TRANSACTIONS_AXON_JDBC_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
axon:
  axonserver:
    servers: localhost
  eventhandling:
    processors:
      accountNumber:
        mode: subscribing
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"